config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'

  resources :movies do
    collection do
      get :rest
      post :change_count
    end
  end

  resource :cart, only: [:show] do
    put 'add/:movie_id', to: 'carts#add', as: :add_to
    put 'remove/:movie_id', to: 'carts#remove', as: :remove_from
    member do
      post :buy
    end
  end

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' },
             controllers: { registrations: 'users/registrations' }

  resources :users, only: [:index] do
    member do
      get :movies
    end
  end

  resources :roles, only: [:new, :create] do
    collection do
      post :change_role
    end
  end

  resources :feedbacks, only: [:new, :create]

  mount Commontator::Engine => '/commontator'
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :should_be_seller, only: [:new, :create]

  def index
    @movies = Movie.paginate page: params[:page], per_page: per_page
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.create movie_params
    redirect_to movie_path @movie.id
  end

  def show
    @movie = Movie.find(params[:id])
    @cart_action = @movie.cart_action current_user.try :id
    commontator_thread_show @movie
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    @movie = Movie.find params[:id]
    @movie.update_attributes movie_params
    redirect_to movie_path(params[:id])
  end

  def destroy
    @movie = Movie.find params[:id]
    if !current_user
      flash[:alert] = 'Please Sign In'
      redirect_to new_user_session_path
    elsif current_user.role.deleting == 0 || (current_user.role.deleting == 1 && @movie.seller_id != current_user.id)
      flash[:alert] = 'Forbidden'
      return redirect_to root_path
    end
    @movie.destroy
    redirect_to root_path
  end

  def rest
    @movies = Movie.all
  end

  def change_count
    @movie = Movie.find params[:id]
    @movie.update_attributes count_of_copies: params[:count]
    render json: { status: true, id: @movie.id, count: @movie.count_of_copies }
  end

  private
  def should_be_seller
    if !current_user
      flash[:alert] = 'Please Sign In'
      redirect_to new_user_session_path
    #elsif current_user.role.creating == 0
    elsif current_user.role_id == 0
      flash[:alert] = 'Forbidden'
      redirect_to root_path
    end
  end

  def movie_params
    params.require(:movie).permit(:title, :release_year, :price, :description, :imdb_id, :poster_url, :seller_id, :count_of_copies, :thrailer_url)
  end

  def per_page
    params[:per_page] || 12
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_for movie do |f| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, 'error') %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title, class: 'radius', placeholder: :title, value: movie.title %>
  </div>

  <div class="field">
    <%= f.number_field :release_year, class: 'radius', placeholder: :release_year, value: movie.release_year %>
  </div>

  <div class="field">
    <%= f.text_field :price, class: 'radius', placeholder: :price, value: movie.price %>
  </div>

  <div class="field">
    <%= f.text_area :description, class: 'radius', placeholder: :description, rows: 5, value: movie.description %>
  </div>

  <div class="field">
    <%= f.text_field :imdb_id, class: 'radius', placeholder: :imdb_id, value: movie.imdb_id %>
  </div>

  <div class="field">
    <div class="small-9 large-10 column p0">
      <%= f.text_field :poster_url, class: 'radius', placeholder: :poster_url, value: movie.poster_url %>
    </div>
    <div class="small-3 large-2 column pr0">
      <a href="#" class="button radius" id="preview">Preview</a>
    </div>
  </div>

  <div class="field">
    <%= f.text_field :count_of_copies, class: 'radius', placeholder: :count_of_copies, value: movie.count_of_copies %>
  </div>

  <div class="field">
    <%= f.text_field :thailer_url, class: 'radius', placeholder: "e.g. https://www.youtube.com/embed/So97pmyDbVw", value: movie.thrailer_url %>
  </div>

  <%= f.hidden_field :seller_id, value: movie.seller_id || current_user.id %>
<% end %>
<% if updating %>
  <%= form_tag movie_path(movie.id),
                data: { confirm: 'Are you sure?' }, method: :delete,
                id: 'delete_movie' do %>
  <% end %>
<% end %>
<div class="actions">
  <% if updating %>
    <%= submit_tag 'Update Movie', form: "edit_movie_#{movie.id}", class: 'button radius',
                                   onclick: "!this.form&&$('#'+$(this).attr('form')).submit()" %>
    <%= submit_tag 'Delete Movie', form: 'delete_movie', class: 'button radius',
                                   onclick: "!this.form&&$('#'+$(this).attr('form')).submit()"%>
  <% else %>
    <%= submit_tag 'Create Movie', form: 'new_movie', class: 'button radius',
                                   onclick: "!this.form&&$('#'+$(this).attr('form')).submit()"%>
  <% end %>
</div>

app/views/movies/_list.html.erb
<div class="column">

  <ul class="movies-grid no-bullet row">
    <% @movies.each do |movie| %>
      <li class="large-3 medium-4 small-12 column">
        <div class="movie-card padly">
          
          <%= link_to movie, class: "poster" do %>
            <%#= image_tag movie.poster, alt: movie.title %>

             <iframe width="220" height="325" src="<%= movie.thrailer_url %>" frameborder="0" gesture="media" allow="encrypted-media", alt: movie.poster ></iframe>

            <div class="movie-info ell glassy-bg padmy padlx">
            <div class="title">
              <h6><%= movie.title %> <span>(<%= movie.release_year %>)</span></h6>
            </div>

            <p class="left price label movie-label radius">$ <%= movie.price %></p>
          
            <%= link_to movie.imdb, class: "right" do %>
              <%= image_tag asset_path("imdb_logo.png") %>
            <% end %>

          </div>

          <% end %>
        </div>
        
      </li>
    <% end %>

  </ul>
  
  <%= will_paginate @movies %>

</div>

app/views/movies/edit.html.erb
<div class="large-12 medium-12 small-12 column">
  <h1>Edit Movie</h1>
</div>

<div class="large-3 medium-3 small-12 column">
  <%= image_tag @movie.poster_url, id: 'poster-preview' %>
</div>
<div class="large-9 medium-9 small-12 column">
  <%= render 'form', movie: @movie, updating: true %>
</div>

<div class="large-12 medium-12 small-12 column">
  <%= link_to 'Back', movie_path(@movie.id) %>
</div>

app/views/movies/index.html.erb
<h4 class="inline p15left">Featured Movies</h4>
<%# if current_user && current_user.role.creating == 1 %>
<% if current_user && current_user.role_id == 1 %>
  <%= link_to 'Add Movie', new_movie_path, class: 'button p15 right mb0 radius' %>
<% end %>
<%= render 'movies/list' %>

app/views/movies/new.html.erb
<div class="large-12 medium-12 small-12 column">
  <h1>New Movie</h1>
</div>

<div class="large-3 medium-3 small-12 column">
  <%= image_tag '/default_poster.jpg', id: 'poster-preview' %>
</div>
<div class="large-9 medium-9 small-12 column">
  <%= render 'form', movie: @movie, updating: false %>
</div>

<div class="large-12 medium-12 small-12 column">
  <%= link_to 'Back', movies_path %>
</div>

app/views/movies/rest.html.erb
<div class="clearfix p15">
  <h3>Movies List</h3>
  <div class="large-8 medium-10 small-12 column small-centered">
    <div class="large-6 medium-5 small-12 column mbm mt0"><strong>Email</strong></div>
    <div class="large-3 medium-3 small-12 column mbm mt0"><strong>Year</strong></div>
    <div class="large-3 medium-4 small-12 column mbm mt0"><strong>Count of Copies</strong></div>
    <% @movies.each do |movie| %>
      <div class="large-6 medium-5 small-12 column mbm mtm"><%= movie.title %></div>
      <div class="large-3 medium-3 small-12 column mbm mtm"><%= movie.release_year %></div>
      <% if current_user.role.updating == 1 %>
        <div class="large-3 medium-4 small-12 column mbs mt0">
          <%= number_field :movie, :count_of_copies, class: 'mbs mt0 radius movie-field',
                           value: movie.count_of_copies, id: "movie_count_of_copies-#{movie.id}" %>
        </div>
      <% else %>
        <div class="large-3 medium-4 small-12 column mbm mtm"><%= movie.count_of_copies %></div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/movies/show.html.erb
<% provide :title, @movie.title %>

<div class="large-3 medium-3 small-12 column">
  <%#= image_tag @movie.poster %>
  <iframe width="220" height="325" src="<%= @movie.thrailer_url %>" frameborder="0" gesture="media" allow="encrypted-media"></iframe>
</div>

<div class="large-6 medium-6 small-9 column">
  <h3>
    <%= @movie.title %>
    (<%= @movie.release_year %>)
    <%= link_to @movie.imdb do %>
      <%= image_tag asset_path('imdb_logo.png') %>
    <% end %>
  </h3>
</div>

<div class="large-3 medium-3 small-3 column">
  <% if current_user && (current_user.role_id == 2 ||
    (current_user.role_id == 1 && @movie.seller_id == current_user.id)) %>
    <%= link_to 'Edit Movie', edit_movie_path(@movie.id), class: 'button p15 right mb0 radius' %>
  <% end %>
</div>

<div class="large-9 medium-9 small-12 column">
  <p class="label movie-label radius mb1">$ <%= @movie.price %></p>

  <p><%= @movie.description %></p>
<!--/div-->

<% if signed_in? && current_user.role_id == 1 %>
  <%= link_to '', class: 'button radius', data: { target:    @cart_action, addUrl: add_to_cart_path(@movie),
                                               removeUrl: remove_from_cart_path(@movie)} do %>
    <i class="fi-shopping-cart"></i>
    <span><%= @cart_action %></span> Cart
  <% end %>
<% end %>
<!--div class="large-9 small-12 column"-->
  <%= commontator_thread(@movie) %>
</div>