config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'

  resources :movies do
    collection do
      get :rest
      post :change_count
    end
  end

  resource :cart, only: [:show] do
    put 'add/:movie_id', to: 'carts#add', as: :add_to
    put 'remove/:movie_id', to: 'carts#remove', as: :remove_from
    member do
      post :buy
    end
  end

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' },
             controllers: { registrations: 'users/registrations' }

  resources :users, only: [:index] do
    member do
      get :movies
    end
  end

  resources :roles, only: [:new, :create] do
    collection do
      post :change_role
    end
  end

  resources :feedbacks, only: [:new, :create]

  mount Commontator::Engine => '/commontator'
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :movie, inverse_of: :carts
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @cart_movies = current_user.bought_movies
    @count = @cart_movies.where('movies.count_of_copies > 0').count
  end

  def buy
    @cart_movies = current_user.bought_movies.where('movies.count_of_copies > 0')
    @cart_movies.each do |movie|
      current_user.carts.find_by(movie_id: movie.id).update_attributes paid: true
      movie.update_attributes count_of_copies: movie.count_of_copies - 1
    end
    flash[:notice] = 'Successfully Bought'
    redirect_to cart_path
  end

  def add
    current_user.carts.create movie_id: params[:movie_id]
    render json: current_user.cart_count, status: 200
  end

  def remove
    current_user.carts.find_by(movie_id: params[:movie_id]).destroy
    render json: current_user.cart_count, status: 200
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<% provide :title, 'My Cart' %>
<div id="mycart" class="small-10 small-centered medium-8 large-8 column">
  <div class="p1 glassy-bg mb1 text-center radius-l1 radius-r1">
    <h4>My Cart</h4>
    <p class="mb0"> You've selected <span class="cart-count"><%= current_user.cart_count %></span> movies!</p>
  </div>

  <% @cart_movies.each do |movie| %>
    <div data-equalizer class="cart-movie medium-12 small-12 large-12 column mb1">
      <div class="column large-2 medium-2 small-2 text-center p0" data-equalizer-watch>
        <%= link_to movie do %>
          <%= image_tag movie.poster, class: 'radius-l1' %>
        <% end %>
      </div>
      <div class="column large-7 medium-7 small-7 glassy-bg text-center" data-equalizer-watch>
        <p class="scale ptm"> <%= movie.title %> <em class="info"><%= movie.count_of_copies == 0 ? '(No Copies)' : nil %></em> </p>
      </div>
      <div class="column large-3 medium-3 small-3 primary-bg text-center radius-r1" data-equalizer-watch>
        <%= link_to '', data: { targetUrl: remove_from_cart_path(movie)} do %>
          <i class="fi-x right"></i>
        <% end %>
        <h4 class="scale">$ <%= movie.price %></h4>
      </div>
    </div>
  <%end%>
  <div class="large-12 medium-12 small-12 column text-center">
    <% if @count > 0 %>
      <%= button_to 'Buy Movies', buy_cart_path, class: 'button radius', data: { confirm: "Buy #{@count} Movies?"} %>
    <% end %>
  </div>
</div>