config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'

  resources :movies do
    collection do
      get :rest
      post :change_count
    end
  end

  resource :cart, only: [:show] do
    put 'add/:movie_id', to: 'carts#add', as: :add_to
    put 'remove/:movie_id', to: 'carts#remove', as: :remove_from
    member do
      post :buy
    end
  end

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' },
             controllers: { registrations: 'users/registrations' }

  resources :users, only: [:index] do
    member do
      get :movies
    end
  end

  resources :roles, only: [:new, :create] do
    collection do
      post :change_role
    end
  end

  resources :feedbacks, only: [:new, :create]

  mount Commontator::Engine => '/commontator'
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController

  def create
    @email = params[:email]
    @content = params[:content]

    EmailJob.perform_now(@email, @content)

    flash[:notice] = 'Successfully Sent Feedback'
    redirect_to root_path
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/new.html.erb
<div class="form-container radius-box small-10 small-centered medium-8 large-6 columns">
  <h3>Write Feedback</h3>
  <%= form_tag feedbacks_path do %>

    <%= email_field_tag :email, nil, placeholder: 'Email', class: 'radius' %>

    <%= text_area_tag :content, nil, placeholder: 'Feedback Content', rows: 7, class: 'radius' %>

    <%= submit_tag 'Send Feedback', class: 'button radius' %>
  <% end %>
</div>