config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'

  resources :movies do
    collection do
      get :rest
      post :change_count
    end
  end

  resource :cart, only: [:show] do
    put 'add/:movie_id', to: 'carts#add', as: :add_to
    put 'remove/:movie_id', to: 'carts#remove', as: :remove_from
    member do
      post :buy
    end
  end

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' },
             controllers: { registrations: 'users/registrations' }

  resources :users, only: [:index] do
    member do
      get :movies
    end
  end

  resources :roles, only: [:new, :create] do
    collection do
      post :change_role
    end
  end

  resources :feedbacks, only: [:new, :create]

  mount Commontator::Engine => '/commontator'
end

app/views/layouts/_alerts.html.erb
<% if notice.present? || alert.present? %>
  <div class="row" id="alert-div">
    <% is_alert = alert.present? ? 'alert' : '' %>
    <div data-alert class="alert-box <%= is_alert %>">
      <%= notice || alert %>
      <a href="#" class="close" onclick="$('#alert-div').css('display', 'none')">&times;</a>
    </div>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<div class="row">
  <nav class="top-bar column" data-topbar>

    <ul class="title-area">
      <li class="name">
        <h1>
          <a href="/">
            <i class="fi-play-video"></i> MovieStore
          </a>
        </h1>
      </li>
      <li class="toggle-topbar"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%if signed_in?%>
          <li>
            <%= link_to cart_path do%>
              <i class="fi-shopping-cart"></i>
              My Cart
              (<span class="cart-count"><%=current_user.cart_count%></span>)
            <%end%>
          </li>
          <li><%=link_to current_user.name, current_user.path %></li>
          <li><%=link_to 'Logout', destroy_user_session_path, method: :delete%></li>
        <%else%>
          <li><%=link_to 'Register', new_user_registration_path%></li>
          <li><%=link_to 'Login', new_user_session_path%></li>
        <%end%>
      </ul>
    </section>

  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : 'MovieStore' %></title>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= favicon_link_tag 'logo.png' %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render 'layouts/header' %>

    <%= render 'layouts/alerts' %>

    <div id="main-content" class="row full-min-height">
      <%= yield %>
    </div>

    <footer class="row">
      <div class="large-12 columns">
        <hr> <p class="inline pb1">&copy; MovieStore 2016</p>
        <%= link_to 'Write Feedback', new_feedback_path, class: 'right pb1' %>
      </div>
    </footer>

  </body>
</html>